server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认 1 M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认 10 M

aliyun:
  vod:
    keyid: 666
    keysecret: 666
    templateGroupId: 666 # 转码模板组 id
    workflowId: 666 # 工作流 id