server:
  port: 8180 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-statistics # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos 服务地址
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
  datasource: # mysql 数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shenlan_statistics?serverTimezone=GMT%2B8
    username: username
    password: password
  #spring:
  jackson: # 返回 json 的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis 日志
  mapper-locations: classpath:com/zfans/shenlan/service/statistics/mapper/xml/*.xml

ribbon:
  ConnectTimeout: 10000 # 连接建立的超时时长，默认 1 秒
  ReadTimeout: 10000 # 处理请求的超时时间，默认为 1 秒

feign:
  sentinel:
    enabled: true